vich_uploader:
    db_driver: orm
    mappings:
        images:
            uri_prefix:         '%app.path.images%'
            upload_destination: '%kernel.project_dir%/public%app.path.images%'
        videos:
            uri_prefix: '%app.path.videos%'
            upload_destination: '%kernel.project_dir%/public%app.path.videos%'